language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.3
  - nightly
branches:
  only:
    - master
    - /^release-.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
notifications:
  email: false
script:
    - julia --project -e 'import Pkg; Pkg.build(); Pkg.test(coverage=true)'
    - julia --project="" -e 'using Pkg; Pkg.add([
        PackageSpec(url="https://github.com/JuliaLang/PackageCompiler.jl", rev="master"),
        PackageSpec(url="https://github.com/JuliaComputing/MKL.jl", rev="kc/mkl_jll_packagecompiler"),
        ])'
    - julia --project -e 'import Pkg; Pkg.build(); Pkg.test(coverage=true)'
